### ISSUE TITLE
Panel within Tab

### ISSUE THREAD

**Issue by antlusher** [dkulyk/nova-tabs#20]
Hello @dkulyk . I'm trying to create a panel within a tab, I've read your documentation, but I can't find a way to do this. Do you know of a way?

Cheers

**Comment by florentpoujol** [comment]
Hello there

FYI you cannot have panels within a tab since v1.1.7. 
The example at https://github.com/dkulyk/nova-tabs#tabs-panel doesn't work anymore.
The fields within the panel, instead of appearing in their own tab, appear inside the "main" tab.

 It works in v1.1.6.
Or as a workaround, you have to do like the other example (with 2 actual tabs) https://github.com/dkulyk/nova-tabs#tabs-panel-with-toolbar
